svtav1: switch to last known good commit
unbreak ffmpeg build

```
libavcodec/libsvtav1.c: In function 'eb_enc_init':
libavcodec/libsvtav1.c:438:61: error: passing argument 2 of 'svt_av1_enc_init_handle' from incompatible pointer type [-Wincompatible-pointer-types]
  438 |     svt_ret = svt_av1_enc_init_handle(&svt_enc->svt_handle, svt_enc, &svt_enc->enc_params);
      |                                                             ^~~~~~~
      |                                                             |
      |                                                             SvtContext *
In file included from libavcodec/libsvtav1.c:25:
/opt/ffbuild/include/svt-av1/EbSvtAv1Enc.h:1128:31: note: expected 'EbSvtAv1EncConfiguration *' but argument is of type 'SvtContext *'
 1128 |     EbSvtAv1EncConfiguration *config_ptr); // config_ptr will be loaded with default params from the library
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
libavcodec/libsvtav1.c:438:15: error: too many arguments to function 'svt_av1_enc_init_handle'
  438 |     svt_ret = svt_av1_enc_init_handle(&svt_enc->svt_handle, svt_enc, &svt_enc->enc_params);
      |               ^~~~~~~~~~~~~~~~~~~~~~~
/opt/ffbuild/include/svt-av1/EbSvtAv1Enc.h:1122:20: note: declared here
 1122 | EB_API EbErrorType svt_av1_enc_init_handle(
      |                    ^~~~~~~~~~~~~~~~~~~~~~~
make: *** [ffbuild/common.mak:81: libavcodec/libsvtav1.o] Error 1
make: *** Waiting for unfinished jobs....
```

Signed-off-by: nanake <nanake@users.noreply.github.com>