libssh: add missing requires api
ffmpeg linking error

```
x86_64-w64-mingw32ucrt/bin/ld: /opt/ffbuild/lib/libssh.a(misc.c.obj):misc.c:(.text+0x3c8): undefined reference to `if_nametoindex'
collect2: error: ld returned 1 exit status
```

triggered by commit https://gitlab.com/libssh/libssh-mirror/-/commit/2c92e8ce930a428a6fd150ae1ae55c5a365543f5

Signed-off-by: nanake <nanake@users.noreply.github.com>