Drop win32 build
Fedora mingw32 has reverted the C runtime from UCRT (default since v12)
back to MSVCRT. [1][2]

Updating mingw-headers to the latest git commit (since commit 469e8e4)
causes ffmpeg build failures when linking against libssh, resulting in
an error `undefined reference to `_imp____timezone'`

This requires rebuilding mingw32-crt, which is impractical for this
toolchain. As such, if it can no longer access to newer Windows API,
I prefer to drop the win32 build instead of pinning its header to the
last known good commit.

However, if anyone is interested in the win32 build, you can build it
yourself and have 2 options:

(a) revert commit 469e8e4 or (b) apply following patch:

```
diff --git a/scripts.d/10-mingw.sh b/scripts.d/10-mingw.sh
--- a/scripts.d/10-mingw.sh
+++ b/scripts.d/10-mingw.sh
@@ -19,4 +19,10 @@

 ffbuild_dockerbuild() {
+    # Fix libssh breakage when linking into FFmpeg (mingw-w64@469e8e4)
+    # Error: undefined reference to `_imp____timezone'
+    if [[ $TARGET == win32 ]]; then
+        MINGW_COMMIT="4517417c018c12de387207e51e0f3728c5164e50"
+    fi
+
     git-mini-clone "$MINGW_REPO" "$MINGW_COMMIT" mingw
     cd mingw/mingw-w64-headers
diff --git a/scripts.d/10-mingw.sh b/scripts.d/10-mingw.sh
--- a/scripts.d/10-mingw.sh
+++ b/scripts.d/10-mingw.sh
@@ -32,4 +38,10 @@
     )

+    if [[ $TARGET == win32 ]]; then
+        myconf+=(
+            --with-default-msvcrt=msvcrt
+        )
+    fi
+
     ./configure "${myconf[@]}"
     make -j"$(nproc)"
```

[1] https://src.fedoraproject.org/rpms/mingw-crt/c/2b816fac2cc3d431ad84af233f2ed5a68c575f5b?branch=rawhide
[2] https://bugzilla.redhat.com/show_bug.cgi?id=2314420

Signed-off-by: nanake <nanake@users.noreply.github.com>